# Generated by Django 4.2.6 on 2024-02-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postmodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('post', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Postmodes',
        ),
    ]
