# Generated by Django 4.2.6 on 2024-02-05 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_postmodels_delete_postmodes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodels',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='postmodels',
            name='author',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postmodels',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
