# Generated by Django 4.2.6 on 2024-02-07 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_name_postmodels_title_postmodels_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodels',
            name='image',
        ),
        migrations.AddField(
            model_name='postmodels',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
