# Generated by Django 4.2.6 on 2024-02-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_postmodels_image_postmodels_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodels',
            name='author',
            field=models.CharField(max_length=20, verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='postmodels',
            name='post',
            field=models.CharField(max_length=1000, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='postmodels',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='投稿日時'),
        ),
        migrations.AlterField(
            model_name='postmodels',
            name='title',
            field=models.CharField(max_length=100, verbose_name='タイトル'),
        ),
    ]
