# Generated by Django 4.2.6 on 2024-02-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_postmodels_author_alter_postmodels_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodels',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='画像'),
        ),
    ]
