# Generated by Django 4.2.6 on 2024-02-09 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_postmodels_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodels',
            old_name='author',
            new_name='user',
        ),
    ]
