# Generated by Django 4.2.6 on 2024-02-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_rename_author_postmodels_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodels',
            name='media2',
            field=models.ImageField(blank=True, null=True, upload_to='photo', verbose_name='画像2'),
        ),
        migrations.AlterField(
            model_name='postmodels',
            name='media',
            field=models.ImageField(upload_to='photo', verbose_name='画像'),
        ),
    ]
