# Generated by Django 4.2.6 on 2024-03-18 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_remove_postmodels_media2_alter_postmodels_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodels',
            name='user',
        ),
    ]
