# Generated by Django 4.2.6 on 2024-03-13 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodels',
            old_name='published_date',
            new_name='publishe_date',
        ),
        migrations.RenameField(
            model_name='commentmodels',
            old_name='user',
            new_name='users',
        ),
    ]
